# Generated by Django 4.0.2 on 2023-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_total_sales_product_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
